(function () {
  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

  const def = {
    id: 'hacker_news', type: 'platform',

    slice: [
      "hn_thread",
      "community_signal_hn_1",
      "community_signal_hn_2",
      "community_signal_hn_3",
      "community_signal_reddit_1",
      "community_signal_reddit_2",
      "community_signal_reddit_3",
      "community_signal_slack_1",
      "community_signal_slack_2",
      "community_signal_slack_3",
      "community_product_hn",
      "community_product_reddit",
      "community_product_slack",
      "yc_discussion_ready",
      "yc_discussion_early",
    ],

    role: "Communities",
    name: "HN / Reddit",  // chat display name
    voice: {
      "hn_thread|engage": "Engaged the HN thread authentically. 7 DMs requesting early access.",
      "community_signal_hn_1|engage": "Commented on the HN thread with a genuine take. 4 people DM'd asking when we're launching.",
      "community_signal_hn_1|skip": "Read the HN thread. Nothing actionable right now.",
      "community_signal_hn_2|engage": "Left a detailed reply on the HN thread. Two people asked to be notified at launch — one is a former PM at a big company.",
      "community_signal_hn_2|skip": "Didn't engage the HN thread. Kept building.",
      "community_signal_hn_3|engage": "Shared the waitlist link on HN. 8 signups from the thread. One person asked to beta test.",
      "community_signal_hn_3|skip": "Watched the HN thread from the sidelines. Three potential users moved on.",
      "community_signal_reddit_1|engage": "Joined the Reddit conversation as a builder. 2 people signed up for early access.",
      "community_signal_reddit_1|skip": "Skipped the Reddit thread. Staying focused.",
      "community_signal_reddit_2|engage": "Added my take on why anti-Tinder startups keep failing. 12 upvotes, 3 private follow-ups.",
      "community_signal_reddit_2|skip": "Took notes from the Reddit thread. Three failure modes to avoid.",
      "community_signal_reddit_3|engage": "Jumped into the Reddit thread as the founder. Thread stayed warm for two days. 7 signups.",
      "community_signal_reddit_3|watch": "Let the Reddit thread run on its own. 3 signups without lifting a finger.",
      "community_signal_slack_1|engage": "Posted an honest update on Indie Hackers. 5 people followed up with their own experiences.",
      "community_signal_slack_1|skip": "Skipped the Indie Hackers thread. Head down this week.",
      "community_signal_slack_2|engage": "Replied to the dating app post-mortem on Indie Hackers with what we're doing differently. The author DM'd me.",
      "community_signal_slack_2|skip": "Took notes from the IH post-mortem. Three failure modes to avoid.",
      "community_signal_slack_3|engage": "Started posting weekly updates on Indie Hackers. 6 new subscribers in 48 hours. Two founders reached out.",
      "community_signal_slack_3|skip": "Stayed quiet on Indie Hackers. The gap with other builders is widening.",
      "community_product_hn|engage": "Responded to every comment on the HN post about us. Thread stayed warm for 3 days. 5 signups.",
      "community_product_hn|watch": "Let the HN post run. Thread faded quickly. 1 signup.",
      "community_product_reddit|engage": "Thanked the Reddit poster publicly and privately. They became a power user and wrote a short review.",
      "community_product_reddit|watch": "Let the Reddit post ride. 2 more signups from the thread tail.",
      "community_product_slack|engage": "Answered pricing questions on the IH post honestly. 2 signups, 1 feature request worth exploring.",
      "community_product_slack|watch": "Let the IH post run. 1 signup.",
      "yc_discussion_ready|apply": "Committed to this YC batch. Deadline is next sprint — time to write the application.",
      "yc_discussion_ready|skip": "Decided to skip this YC batch. Next one opens in ~12 weeks.",
      "yc_discussion_early|apply": "Going for YC anyway — a long shot, but the partner feedback alone is worth it.",
      "yc_discussion_early|skip": "Waiting for the next YC batch. More time to hit the numbers."
    },
    cards: [
      {
        id: 'hn_thread', cat: 'e', from: 'Hacker News',
        body: "'Ask HN: Why are dating apps still so bad in 2026?' — top thread right now, 300 comments. this is your market talking openly.",
        urgency: 2, weeks: 1,
        available: (s) => !s.launched && !s.hn_thread_done,
        options: [
          { label: 'Engage the thread', key: 'engage',
            execute(s) { s.hn_thread_done = true; s.signal = clamp(s.signal + 12, 0, 100); s.market_fit = clamp(s.market_fit + 3, 0, 100); s.waitlist += 7; s.network.peers += 8; return "Engaged the thread authentically. 7 DMs requesting early access."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s) { s.hn_thread_done = true; s.signal = clamp(s.signal - 3, 0, 100); },
      },
      // ── SEQUENCE: pre-launch HN signal (3 one-shot cards) ───────────────────
      {
        id: 'community_signal_hn_1', cat: 'e', from: 'Hacker News',
        body: "there's an Ask HN thread about what's broken with dating apps. 200 comments. the top answer is a shared Google spreadsheet where people manually track matches across apps. it has 50,000 views.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && s.week >= 6 && (char.flags.hn_stage || 0) === 0,
        options: [
          { label: 'Drop a comment', key: 'engage',
            execute(s, char) { char.flags.hn_stage = 1; char.flags.hn_stage_week = s.week; s.signal = clamp(s.signal + 6, 0, 100); s.waitlist += 4; s.network.peers += 3; s.market_fit = clamp(s.market_fit + 1, 0, 100); return "Commented with a genuine take. 4 people DM'd asking when you're launching."; } },
          { label: 'Read and move on', key: 'skip',
            execute(s, char) { char.flags.hn_stage = 1; char.flags.hn_stage_week = s.week; return "Read it. Nothing actionable right now."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.hn_stage = 1; char.flags.hn_stage_week = s.week; },
      },
      {
        id: 'community_signal_hn_2', cat: 'e', from: 'Hacker News',
        body: "another HN thread about dating apps, bigger this time. people are explicitly asking for something that actually helps — not another swipe interface.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && char.flags.hn_stage === 1 && s.week >= (char.flags.hn_stage_week || 0) + 5,
        options: [
          { label: 'Leave a detailed reply', key: 'engage',
            execute(s, char) { char.flags.hn_stage = 2; char.flags.hn_stage_week = s.week; s.signal = clamp(s.signal + 7, 0, 100); s.waitlist += 5; s.network.peers += 4; return "Left a detailed reply. Two people asked to be notified at launch. One is a former PM at a big company."; } },
          { label: 'Leave it', key: 'skip',
            execute(s, char) { char.flags.hn_stage = 2; char.flags.hn_stage_week = s.week; return "Didn't engage. Kept building."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.hn_stage = 2; char.flags.hn_stage_week = s.week; },
      },
      {
        id: 'community_signal_hn_3', cat: 'e', from: 'Hacker News',
        body: "someone posted your exact frustration as an HN thread. it hit the front page. three comments specifically mention wanting a real product, not 'tinder but slightly different.'",
        urgency: 2, weeks: 1,
        available: (s, char) => !s.launched && char.flags.hn_stage === 2 && s.week >= (char.flags.hn_stage_week || 0) + 5,
        options: [
          { label: 'Share the waitlist link', key: 'engage',
            execute(s, char) { char.flags.hn_stage = 3; s.signal = clamp(s.signal + 9, 0, 100); s.waitlist += 8; s.network.peers += 5; s.market_fit = clamp(s.market_fit + 2, 0, 100); return "Shared the link. 8 signups from the thread. One person asked to beta test — you said yes."; } },
          { label: 'Stay quiet for now', key: 'skip',
            execute(s, char) { char.flags.hn_stage = 3; s.signal = clamp(s.signal + 2, 0, 100); return "Watched from the sidelines. Three potential users moved on. The thread died."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.hn_stage = 3; },
      },

      // ── SEQUENCE: pre-launch Reddit signal (3 one-shot cards) ───────────────
      {
        id: 'community_signal_reddit_1', cat: 'e', from: 'Reddit',
        body: "r/datingapps — top post this week: 'what apps do you actually use and why?' 200 comments, mostly complaints about ghosting and time-wasters.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && s.week >= 8 && (char.flags.reddit_stage || 0) === 0,
        options: [
          { label: 'Join the conversation', key: 'engage',
            execute(s, char) { char.flags.reddit_stage = 1; char.flags.reddit_stage_week = s.week; s.signal = clamp(s.signal + 5, 0, 100); s.waitlist += 2; s.market_fit = clamp(s.market_fit + 2, 0, 100); return "Joined as a builder, not a promoter. 2 people signed up for early access."; } },
          { label: 'Skip it', key: 'skip',
            execute(s, char) { char.flags.reddit_stage = 1; char.flags.reddit_stage_week = s.week; return "Skipped. Staying focused."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.reddit_stage = 1; char.flags.reddit_stage_week = s.week; },
      },
      {
        id: 'community_signal_reddit_2', cat: 'e', from: 'Reddit',
        body: "a reddit thread analyzing why the last three 'anti-Tinder' startups all failed. the pattern is uncomfortably familiar.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && char.flags.reddit_stage === 1 && s.week >= (char.flags.reddit_stage_week || 0) + 5,
        options: [
          { label: 'Respond with your read on it', key: 'engage',
            execute(s, char) { char.flags.reddit_stage = 2; char.flags.reddit_stage_week = s.week; s.signal = clamp(s.signal + 5, 0, 100); s.market_fit = clamp(s.market_fit + 4, 0, 100); return "Added your take on where they missed. 12 upvotes. Three people followed up privately."; } },
          { label: 'Take notes and move on', key: 'skip',
            execute(s, char) { char.flags.reddit_stage = 2; char.flags.reddit_stage_week = s.week; s.market_fit = clamp(s.market_fit + 2, 0, 100); return "Read everything. Three things to avoid. Filed away."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.reddit_stage = 2; char.flags.reddit_stage_week = s.week; },
      },
      {
        id: 'community_signal_reddit_3', cat: 'e', from: 'Reddit',
        body: "someone posted your landing page on r/datingapps without asking. 40 upvotes. people in the comments are asking when it launches.",
        urgency: 2, weeks: 1,
        available: (s, char) => !s.launched && char.flags.reddit_stage === 2 && s.week >= (char.flags.reddit_stage_week || 0) + 5,
        options: [
          { label: 'Jump in as the founder', key: 'engage',
            execute(s, char) { char.flags.reddit_stage = 3; s.signal = clamp(s.signal + 8, 0, 100); s.waitlist += 7; s.market_fit = clamp(s.market_fit + 2, 0, 100); return "Jumped in as the founder. Thread stayed warm for two days. 7 signups."; } },
          { label: 'Let it run on its own', key: 'watch',
            execute(s, char) { char.flags.reddit_stage = 3; s.signal = clamp(s.signal + 3, 0, 100); s.waitlist += 3; return "Organic momentum. 3 signups without lifting a finger."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.reddit_stage = 3; },
      },

      // ── SEQUENCE: pre-launch Indie Hackers signal (3 one-shot cards) ─────────
      {
        id: 'community_signal_slack_1', cat: 'e', from: 'Indie Hackers',
        body: "a thread on Indie Hackers: 'how do you validate a consumer social app before you build?' — half the comments describe the exact frustration kindred is trying to solve.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && s.week >= 10 && (char.flags.ih_stage || 0) === 0,
        options: [
          { label: 'Share what you\'ve learned', key: 'engage',
            execute(s, char) { char.flags.ih_stage = 1; char.flags.ih_stage_week = s.week; s.signal = clamp(s.signal + 5, 0, 100); s.network.peers += 4; s.market_fit = clamp(s.market_fit + 1, 0, 100); return "Posted an honest update. 5 people followed up with their own experiences. Real signal."; } },
          { label: 'Skip it', key: 'skip',
            execute(s, char) { char.flags.ih_stage = 1; char.flags.ih_stage_week = s.week; return "Skipped. Head down this week."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.ih_stage = 1; char.flags.ih_stage_week = s.week; },
      },
      {
        id: 'community_signal_slack_2', cat: 'e', from: 'Indie Hackers',
        body: "an indie hacker just published a post-mortem for a dating app that tried your exact angle. failed in month 8. you read every word.",
        urgency: 1, weeks: 1,
        available: (s, char) => !s.launched && char.flags.ih_stage === 1 && s.week >= (char.flags.ih_stage_week || 0) + 5,
        options: [
          { label: 'Reply with what you\'re doing differently', key: 'engage',
            execute(s, char) { char.flags.ih_stage = 2; char.flags.ih_stage_week = s.week; s.signal = clamp(s.signal + 5, 0, 100); s.market_fit = clamp(s.market_fit + 5, 0, 100); s.network.peers += 3; return "Left a detailed reply on what you learned from their mistakes. The author DM'd you. Useful conversation."; } },
          { label: 'Take notes privately', key: 'skip',
            execute(s, char) { char.flags.ih_stage = 2; char.flags.ih_stage_week = s.week; s.market_fit = clamp(s.market_fit + 3, 0, 100); return "Took notes. Three failure modes to avoid. Filed away."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.ih_stage = 2; char.flags.ih_stage_week = s.week; },
      },
      {
        id: 'community_signal_slack_3', cat: 'e', from: 'Indie Hackers',
        body: "indie hackers build-in-public thread for consumer social apps. five founders posting weekly updates. your waitlist is half the size of the least active one.",
        urgency: 2, weeks: 1,
        available: (s, char) => !s.launched && char.flags.ih_stage === 2 && s.week >= (char.flags.ih_stage_week || 0) + 5,
        options: [
          { label: 'Start posting weekly updates', key: 'engage',
            execute(s, char) { char.flags.ih_stage = 3; s.signal = clamp(s.signal + 6, 0, 100); s.waitlist += 6; s.network.peers += 5; return "First public update posted. 6 new subscribers in 48 hours. Two founders reached out to compare notes."; } },
          { label: 'Keep heads down', key: 'skip',
            execute(s, char) { char.flags.ih_stage = 3; return "Stayed quiet. The gap is widening."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char) { char.flags.ih_stage = 3; },
      },

      // ── RECURRING: post-launch product mentions ──────────────────────────────
      {
        id: 'community_product_hn', cat: 'e', from: 'Hacker News',
        body: "someone posted your product on HN. mixed reactions — a few critiques, but 5 people asking how to sign up.",
        urgency: 1, weeks: 1,
        available: (s) => s.launched && s.week >= (s.community_product_hn_last || 0) + 3,
        options: [
          { label: 'Engage the thread', key: 'engage',
            execute(s) { s.community_product_hn_last = s.week; s.signal = clamp(s.signal + 7, 0, 100); s.users += 5; return "Responded to every comment. Thread stayed warm for 3 days. 5 signups."; } },
          { label: 'Let it run', key: 'watch',
            execute(s) { s.community_product_hn_last = s.week; s.users += 1; return "Didn't engage. Thread faded quickly. 1 signup."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s) { s.community_product_hn_last = s.week; },
      },
      {
        id: 'community_product_reddit', cat: 'e', from: 'Reddit',
        body: "someone recommended your product in a thread. comment got 40 upvotes. you're showing up in searches now.",
        urgency: 1, weeks: 1,
        available: (s) => s.launched && s.week >= (s.community_product_reddit_last || 0) + 3,
        options: [
          { label: 'Reach out to the poster', key: 'engage',
            execute(s) { s.community_product_reddit_last = s.week; s.signal = clamp(s.signal + 5, 0, 100); s.users += 3; s.market_fit = clamp(s.market_fit + 1, 0, 100); return "Thanked them publicly and privately. They became a power user and wrote a short review."; } },
          { label: 'Let it ride', key: 'watch',
            execute(s) { s.community_product_reddit_last = s.week; s.users += 2; return "Organic momentum. 2 more signups from the thread tail."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s) { s.community_product_reddit_last = s.week; },
      },

      {
        id: 'community_product_slack', cat: 'e', from: 'Indie Hackers',
        body: "someone posted a 'Show IH' about your product. mostly positive. a few asking about pricing.",
        urgency: 1, weeks: 1,
        available: (s) => s.launched && s.week >= (s.community_product_slack_last || 0) + 3,
        options: [
          { label: 'Engage and answer pricing questions', key: 'engage',
            execute(s) { s.community_product_slack_last = s.week; s.signal = clamp(s.signal + 4, 0, 100); s.users += 2; return "Answered everything honestly. 2 signups, 1 feature request worth exploring."; } },
          { label: 'Let it run', key: 'watch',
            execute(s) { s.community_product_slack_last = s.week; s.users += 1; return "Thread ran its course. 1 signup."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s) { s.community_product_slack_last = s.week; },
      },

      {
        id: 'yc_discussion_ready', cat: 'e', from: 'Hacker News',
        body: "YC applications just opened. Your stats qualify — live product, 10+ paying subscribers. A lot of founders in the consumer social space are applying.",
        urgency: 2, weeks: 1, priority: 1,
        available: (s, char, e) => s.week >= e.ycWeek && !s.ycDeciding && !s.ycApplied && !s.ycAccepted && s.launched && s.customers >= 10,
        options: [
          { label: 'Start writing the application', key: 'apply',
            execute(s, char, e) { s.ycDeciding = true; s.ycQualified = true; return "Committed to this batch. Deadline is next sprint — time to write."; } },
          { label: 'Skip this batch', key: 'skip',
            execute(s, char, e) { e.ycWeek += 12; return "Decided to skip this batch. Next one opens in ~12 weeks."; } },
        ],
        dropDelay: 0, dropMsg: null, dropFx: null,
      },
      {
        id: 'yc_discussion_early', cat: 'e', from: 'Hacker News',
        body: "YC applications just opened. Stats aren't quite there yet — not launched or fewer than 10 paying subscribers. Some apply anyway for partner feedback. Apply or wait?",
        urgency: 2, weeks: 1, priority: 1,
        available: (s, char, e) => s.week >= e.ycWeek && !s.ycDeciding && !s.ycApplied && !s.ycAccepted && (!s.launched || s.customers < 10),
        options: [
          { label: 'Start writing anyway', key: 'apply',
            execute(s, char, e) { s.ycDeciding = true; s.ycQualified = false; return "Going for it — a long shot, but the partner feedback alone is worth it."; } },
          { label: 'Wait for next batch', key: 'skip',
            execute(s, char, e) { e.ycWeek += 12; return "Waiting for next batch. More time to hit the numbers. Next window in ~12 weeks."; } },
        ],
        dropDelay: 0, dropMsg: null,
        dropFx(s, char, e) { e.ycWeek = s.week + 12; },
      },
    ],
  };

  if (typeof module !== 'undefined') module.exports = def;
  else ROLES.hacker_news = def;
})();
